// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "zt6+}G9vUQAbEj6q;OD|":
            case "Player":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fefefbf44fbfeff.........
fbfe41fddf14ef..........
fdffe4dddd4efe..........
fefef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
.....e....ee...e........
.....eee..e..eee........
.......eeeeeee..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
